apiVersion: v1
kind: Secret
metadata:
  name: dev-netbackup-nb-config-deploy-secret
  namespace: dev-netbackup
type: Opaque
stringData:
  apikey: AxCbN8iDc6rDk9RjD5DEZ4VxINhr8YHfRwRGSVRSD5TpFGydAGiUF2a-2sPtD991
