netbackupkops:
  containers:
    manager:
      image:  asia-southeast2-docker.pkg.dev/joey-dev-project/dev-veritas/netbackupkops:netbackupkops_10.4_0018
      resources:
        limits:
          cpu: 150m
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 500Mi
  kopsPvcStorageClass:
  kopsPvcSize: 10Gi
  pvMountPath: /usr/openv
  imagePullSecrets: []
  # Example to add imagePullSecrets
  imagePullSecrets:
  - name: netbackupkops-docker-creds
  fipsMode: DISABLE
  acceleratorTracklogPvcStorageClass: None
nbsetup:
  replicas: 1
  containers:
    netbackup_config_pod:
      nbprimaryserver: PRDNBUMASTER
      nbsha256fingerprint: B0:AB:84:DC:00:DA:08:8A:BA:B1:B1:FF:0A:1D:DC:D4:0A:C3:F7:5C:DB:32:50:62:03:7F:94:3D:7C:06:56:E5
      k8sCluster: dev-id-bks-gke-02
      k8sPort: 6443
      datamoverimage: asia-southeast2-docker.pkg.dev/joey-dev-project/dev-veritas/netbackupdatamover:dev-10.4
      logLevel: INFO
      storageclassblock: standard-rwo
      volumesnapshotclassblock: csi-pd-hostpath-snapclass
      storageclassfilesystem: standard-rwo
      volumesnapshotclassfilesystem: csi-pd-hostpath-snapclass
